# Each Service section represents an autonomous system (ISP) router.
# In the future, interior routers can be added to each ISP to simulate route propagation.
services: 
  horse-isp: 
    build:
      context: ./frr-image
      dockerfile: dockerfile
    container_name: horse-isp
    hostname: horse-isp-border
    environment:
      - ISP_NAME=Horse
      - ASN=100
      - PUBLIC_IPV4_ALLOC=216.177.0.0/16
      - BGP_ROUTER_ID=216.177.0.1
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: /scripts/entrypoint.sh
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
    networks:
      horse-duck-peering:
        ipv4_address: 172.31.0.2

  duck-isp: 
    build:
      context: ./frr-image
      dockerfile: dockerfile
    container_name: duck-isp
    hostname: duck-isp-border
    environment:
      - ISP_NAME=Duck
      - ASN=200
      - PUBLIC_IPV4_ALLOC=50.50.0.0/16
      - BGP_ROUTER_ID=50.50.0.1
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: /scripts/entrypoint.sh
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
    networks:
      horse-duck-peering:
        ipv4_address: 172.31.0.3
      duck-ram-peering:
        ipv4_address: 172.32.0.2

  ram-isp:
    build:
      context: ./frr-image
      dockerfile: dockerfile
    container_name: ram-isp
    hostname: ram-isp-border
    environment:
      - ISP_NAME=Ram
      - ASN=350
      - PUBLIC_IPV4_ALLOC=66.211.0.0/16
      - BGP_ROUTER_ID=66.211.0.1
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: /scripts/entrypoint.sh
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
    networks:
      duck-ram-peering:
        ipv4_address: 172.32.0.3

# Each network suffixed with -peering emulates a direct peering connection between two ISPs.

networks:
  horse-duck-peering:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/24

  duck-ram-peering:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.32.0.0/24